[package]
name = "cartesi-compute"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "cartesi-compute-server"
path = "src/server.rs"

[dependencies]
tonic = "0.9.2"
prost = "0.11.9"
tokio = { version = "1.29.1", features = ["full"] }

[build-dependencies]
tonic-build = "0.9.2"
