concerns:
  - abi: "../node_modules/@cartesi/arbitration/build/contracts/PartitionInstantiator.json"
    user_address: <USER_ADDRESS>
  - abi: "../node_modules/@cartesi/arbitration/build/contracts/MMInstantiator.json"
    user_address: <USER_ADDRESS>
  - abi: "../node_modules/@cartesi/arbitration/build/contracts/VGInstantiator.json"
    user_address: <USER_ADDRESS>
main_concern:
  abi: "../build/contracts/Descartes.json"
  user_address: <USER_ADDRESS>
confirmations: 12
max_delay: 500
query_port: 12345
services:
  - name: emulator
    transport:
      address: 123
      port: 123
  - name: logger
    transport:
      address: 123
      port: 123
testing: true
url: http://localhost:8545
warn_delay: 30
polling_interval: 15
web3_timeout: 10
