{% set players = num_players | int %}
version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    command: ["ganache-cli", "--accounts", "{{ players }}", "--account_keys_path", "/ganache-data/keys"]
    volumes:
      - ganache_data:/ganache-data
    expose:
      - 8545
    ports:
      - 8545:8545
    networks:
      - ethereum

  deployer:
    depends_on: [ganache]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      ETHEREUM_HOST: ganache
      ETHEREUM_NETWORK: ganache
    volumes:
      - ./:/opt/cartesi/share/blockchain
    networks:
      - ethereum

  key_distributor:
    depends_on: [ganache]
    image: cartesi/key-distributor
    volumes:
      - ganache_data:/keys
      {% for i in range(players) %}- key_data_{{ i }}:/key-{{ i }}
      {% endfor %}
  
{% for i in range(players) %}
  dispatcher_{{ i }}:
    image: cartesi/descartes:0.2.0
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info,descartes=trace
      WEB3_PROVIDER_URI: http://ganache:8545
      DEPLOYMENT_SEMAPHORE: file:///opt/cartesi/share/blockchain/deploy_done
      QUERY_PORT: 3001
      MACHINE_MANAGER_HOST: machine-manager
      MACHINE_MANAGER_PORT: 50051
      LOGGER_HOST: logger
      LOGGER_PORT: 50051
      IPFS_HOST: ipfs
      IPFS_PORT: 50051
      DOCKER: "TRUE"
      RUST_BACKTRACE: 1
      CONCERN_SEMAPHORE: file:///opt/cartesi/etc/keys/keys_done
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/descartes
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - dispatcher
    ports:
      - "{{ 3001 + i }}:3001"

  logger_{{ i }}:
    image: cartesi/logger-server:0.4.0
    command: [ "-c", "/opt/cartesi/share/blockchain/node_modules/@cartesi/logger/build/contracts/Logger.json", "-d", "/opt/cartesi/srv/descartes/flashdrive"]
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/descartes
    environment:
      WEB3_PROVIDER_URI: http://ganache:8545
      DEPLOYMENT_SEMAPHORE: file:///opt/cartesi/share/blockchain/deploy_done
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - logger

  ipfs_{{ i }}:
    image: cartesi/ipfs:0.1.0
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/descartes
    networks:
      ipfs: {}
      node_{{ i }}:
        aliases:
          - ipfs
    ports:
        - "{{ 50051 + i }}:50051"

  machine_manager_{{ i }}:
    image: cartesi/machine-manager:0.4.2
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/descartes:ro
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - machine-manager
{% endfor %}

volumes:
  ganache_data:
  {% for i in range(players) %}dapp_data_{{ i }}:
  key_data_{{ i }}:
  {% endfor %}

networks:
  ipfs:
  ethereum:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
