{% set players = num_players | int %}
version: '3'
services:
  hardhatnet:
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
    environment:
      MNEMONIC: "donor rather all fix tongue poverty camera oxygen have length thumb beach"
    expose:
      - 8545
    ports:
      - 8545:8545
    volumes:
      - ./:/opt/cartesi/share/blockchain
    networks:
      - ethereum
  
{% for i in range(players) %}
  dispatcher_{{ i }}:
    image: cartesi/descartes:latest
    restart: always
    environment:
      MNEMONIC: "donor rather all fix tongue poverty camera oxygen have length thumb beach"
      ACCOUNT_INDEX: "{{ i }}"
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info,descartes=trace
      WEB3_PROVIDER_URI: http://hardhatnet:8545
      DEPLOYMENT_SEMAPHORE: http://hardhatnet:8545
      QUERY_PORT: 3001
      MACHINE_MANAGER_HOST: machine-manager
      MACHINE_MANAGER_PORT: 50051
      LOGGER_HOST: logger
      LOGGER_PORT: 50051
      IPFS_HOST: ipfs
      IPFS_PORT: 50051
      DOCKER: "TRUE"
      RUST_BACKTRACE: 1
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - ./dapp_data_{{ i }}/flashdrive:/opt/cartesi/srv/descartes/flashdrive
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - dispatcher
    ports:
      - "{{ 3001 + i }}:3001"

  logger_{{ i }}:
    image: cartesi/logger-server:0.6.2
    command: [ "-c", "/opt/cartesi/share/blockchain/deployments/localhost/Logger.json", "-d", "/opt/cartesi/srv/descartes/flashdrive"]
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - ./dapp_data_{{ i }}/flashdrive:/opt/cartesi/srv/descartes/flashdrive
    environment:
      MNEMONIC: "donor rather all fix tongue poverty camera oxygen have length thumb beach"
      ACCOUNT_INDEX: "{{ i }}"
      WEB3_PROVIDER_URI: http://hardhatnet:8545
      DEPLOYMENT_SEMAPHORE: http://hardhatnet:8545
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - logger

  ipfs_{{ i }}:
    image: cartesicorp/ipfs:0.1.0
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/descartes
    networks:
      ipfs: {}
      node_{{ i }}:
        aliases:
          - ipfs
    ports:
        - "{{ 50051 + i }}:50051"

  machine_manager_{{ i }}:
    image: cartesicorp/machine-manager:0.5.0-rc1
    volumes:
      - ./machines:/opt/cartesi/srv/descartes/cartesi-machine
      - ./dapp_data_{{ i }}/flashdrive:/opt/cartesi/srv/descartes/flashdrive
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - machine-manager
{% endfor %}

volumes:
  {% for i in range(players) %}dapp_data_{{ i }}:
  {% endfor %}

networks:
  ipfs:
  ethereum:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
